/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IInheritanceCore {
  export type TimeLockStruct = {
    distributionType: BigNumberish;
    unlockTime: BigNumberish;
    vestingDuration: BigNumberish;
    cliffDuration: BigNumberish;
    milestoneTimestamps: BigNumberish[];
    milestonePercentages: BigNumberish[];
  };

  export type TimeLockStructOutput = [
    distributionType: bigint,
    unlockTime: bigint,
    vestingDuration: bigint,
    cliffDuration: bigint,
    milestoneTimestamps: bigint[],
    milestonePercentages: bigint[]
  ] & {
    distributionType: bigint;
    unlockTime: bigint;
    vestingDuration: bigint;
    cliffDuration: bigint;
    milestoneTimestamps: bigint[];
    milestonePercentages: bigint[];
  };

  export type BeneficiaryStruct = {
    wallet: AddressLike;
    allocationBasisPoints: BigNumberish;
    isActive: boolean;
    claimedETH: BigNumberish;
    addedAt: BigNumberish;
  };

  export type BeneficiaryStructOutput = [
    wallet: string,
    allocationBasisPoints: bigint,
    isActive: boolean,
    claimedETH: bigint,
    addedAt: bigint
  ] & {
    wallet: string;
    allocationBasisPoints: bigint;
    isActive: boolean;
    claimedETH: bigint;
    addedAt: bigint;
  };

  export type InheritanceDataStruct = {
    owner: AddressLike;
    name: string;
    status: BigNumberish;
    createdAt: BigNumberish;
    triggeredAt: BigNumberish;
    timeLock: IInheritanceCore.TimeLockStruct;
    totalBeneficiaries: BigNumberish;
    requiresConfirmation: boolean;
    executor: AddressLike;
    totalETHDeposited: BigNumberish;
    totalETHClaimed: BigNumberish;
  };

  export type InheritanceDataStructOutput = [
    owner: string,
    name: string,
    status: bigint,
    createdAt: bigint,
    triggeredAt: bigint,
    timeLock: IInheritanceCore.TimeLockStructOutput,
    totalBeneficiaries: bigint,
    requiresConfirmation: boolean,
    executor: string,
    totalETHDeposited: bigint,
    totalETHClaimed: bigint
  ] & {
    owner: string;
    name: string;
    status: bigint;
    createdAt: bigint;
    triggeredAt: bigint;
    timeLock: IInheritanceCore.TimeLockStructOutput;
    totalBeneficiaries: bigint;
    requiresConfirmation: boolean;
    executor: string;
    totalETHDeposited: bigint;
    totalETHClaimed: bigint;
  };

  export type AssetStruct = {
    assetType: BigNumberish;
    contractAddress: AddressLike;
    amount: BigNumberish;
    tokenIds: BigNumberish[];
    isActive: boolean;
    depositedAt: BigNumberish;
  };

  export type AssetStructOutput = [
    assetType: bigint,
    contractAddress: string,
    amount: bigint,
    tokenIds: bigint[],
    isActive: boolean,
    depositedAt: bigint
  ] & {
    assetType: bigint;
    contractAddress: string;
    amount: bigint;
    tokenIds: bigint[];
    isActive: boolean;
    depositedAt: bigint;
  };
}

export declare namespace ITimingManager {
  export type TimingConfigStruct = {
    minVestingDuration: BigNumberish;
    defaultExecutionDelay: BigNumberish;
    defaultCliffDuration: BigNumberish;
    maxVestingDuration: BigNumberish;
    isConfigurable: boolean;
  };

  export type TimingConfigStructOutput = [
    minVestingDuration: bigint,
    defaultExecutionDelay: bigint,
    defaultCliffDuration: bigint,
    maxVestingDuration: bigint,
    isConfigurable: boolean
  ] & {
    minVestingDuration: bigint;
    defaultExecutionDelay: bigint;
    defaultCliffDuration: bigint;
    maxVestingDuration: bigint;
    isConfigurable: boolean;
  };
}

export interface InheritanceCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EMERGENCY_ROLE"
      | "EXECUTOR_ROLE"
      | "OWNER_ROLE"
      | "addBeneficiary"
      | "claimAssets"
      | "createInheritance"
      | "depositERC20"
      | "depositERC721"
      | "depositETH"
      | "getBeneficiaryInfo"
      | "getClaimableETH"
      | "getInheritanceData"
      | "getInheritanceTiming"
      | "getRoleAdmin"
      | "getTotalAssets"
      | "grantRole"
      | "hasRole"
      | "onERC721Received"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeRole"
      | "setCustomTiming"
      | "setProductionMode"
      | "setTestingMode"
      | "setTimingManager"
      | "supportsInterface"
      | "timingManager"
      | "triggerInheritance"
      | "unpause"
      | "updateInheritanceTiming"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetClaimed"
      | "AssetDeposited"
      | "BeneficiaryAdded"
      | "InheritanceCompleted"
      | "InheritanceCreated"
      | "InheritanceTriggered"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addBeneficiary",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createInheritance",
    values: [string, AddressLike, boolean, IInheritanceCore.TimeLockStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC721",
    values: [BigNumberish, AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaryInfo",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableETH",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInheritanceData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInheritanceTiming",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCustomTiming",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProductionMode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestingMode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimingManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timingManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerInheritance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateInheritanceTiming",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OWNER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createInheritance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInheritanceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInheritanceTiming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCustomTiming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProductionMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTestingMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimingManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timingManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerInheritance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateInheritanceTiming",
    data: BytesLike
  ): Result;
}

export namespace AssetClaimedEvent {
  export type InputTuple = [
    inheritanceId: BigNumberish,
    beneficiary: AddressLike,
    assetType: BigNumberish,
    contractAddress: AddressLike,
    amount: BigNumberish,
    tokenIds: BigNumberish[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    inheritanceId: bigint,
    beneficiary: string,
    assetType: bigint,
    contractAddress: string,
    amount: bigint,
    tokenIds: bigint[],
    timestamp: bigint
  ];
  export interface OutputObject {
    inheritanceId: bigint;
    beneficiary: string;
    assetType: bigint;
    contractAddress: string;
    amount: bigint;
    tokenIds: bigint[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetDepositedEvent {
  export type InputTuple = [
    inheritanceId: BigNumberish,
    assetType: BigNumberish,
    contractAddress: AddressLike,
    amount: BigNumberish,
    tokenIds: BigNumberish[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    inheritanceId: bigint,
    assetType: bigint,
    contractAddress: string,
    amount: bigint,
    tokenIds: bigint[],
    timestamp: bigint
  ];
  export interface OutputObject {
    inheritanceId: bigint;
    assetType: bigint;
    contractAddress: string;
    amount: bigint;
    tokenIds: bigint[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryAddedEvent {
  export type InputTuple = [
    inheritanceId: BigNumberish,
    beneficiary: AddressLike,
    allocationBasisPoints: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    inheritanceId: bigint,
    beneficiary: string,
    allocationBasisPoints: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    inheritanceId: bigint;
    beneficiary: string;
    allocationBasisPoints: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceCompletedEvent {
  export type InputTuple = [
    inheritanceId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [inheritanceId: bigint, timestamp: bigint];
  export interface OutputObject {
    inheritanceId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceCreatedEvent {
  export type InputTuple = [
    inheritanceId: BigNumberish,
    owner: AddressLike,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    inheritanceId: bigint,
    owner: string,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    inheritanceId: bigint;
    owner: string;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceTriggeredEvent {
  export type InputTuple = [
    inheritanceId: BigNumberish,
    triggeredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    inheritanceId: bigint,
    triggeredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    inheritanceId: bigint;
    triggeredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InheritanceCore extends BaseContract {
  connect(runner?: ContractRunner | null): InheritanceCore;
  waitForDeployment(): Promise<this>;

  interface: InheritanceCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMERGENCY_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  OWNER_ROLE: TypedContractMethod<[], [string], "view">;

  addBeneficiary: TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      beneficiary: AddressLike,
      allocationBasisPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  claimAssets: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createInheritance: TypedContractMethod<
    [
      name: string,
      executor: AddressLike,
      requiresConfirmation: boolean,
      timeLock: IInheritanceCore.TimeLockStruct
    ],
    [bigint],
    "nonpayable"
  >;

  depositERC20: TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      tokenContract: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  depositERC721: TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      nftContract: AddressLike,
      tokenIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  depositETH: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [void],
    "payable"
  >;

  getBeneficiaryInfo: TypedContractMethod<
    [inheritanceId: BigNumberish, beneficiary: AddressLike],
    [IInheritanceCore.BeneficiaryStructOutput],
    "view"
  >;

  getClaimableETH: TypedContractMethod<
    [inheritanceId: BigNumberish, beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  getInheritanceData: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [IInheritanceCore.InheritanceDataStructOutput],
    "view"
  >;

  getInheritanceTiming: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [ITimingManager.TimingConfigStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalAssets: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [IInheritanceCore.AssetStructOutput[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setCustomTiming: TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      vestingSeconds: BigNumberish,
      delaySeconds: BigNumberish,
      cliffSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setProductionMode: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTestingMode: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTimingManager: TypedContractMethod<
    [_timingManager: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  timingManager: TypedContractMethod<[], [string], "view">;

  triggerInheritance: TypedContractMethod<
    [inheritanceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateInheritanceTiming: TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      minVestingDuration: BigNumberish,
      executionDelay: BigNumberish,
      cliffDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OWNER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addBeneficiary"
  ): TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      beneficiary: AddressLike,
      allocationBasisPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimAssets"
  ): TypedContractMethod<[inheritanceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createInheritance"
  ): TypedContractMethod<
    [
      name: string,
      executor: AddressLike,
      requiresConfirmation: boolean,
      timeLock: IInheritanceCore.TimeLockStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositERC20"
  ): TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      tokenContract: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositERC721"
  ): TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      nftContract: AddressLike,
      tokenIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositETH"
  ): TypedContractMethod<[inheritanceId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getBeneficiaryInfo"
  ): TypedContractMethod<
    [inheritanceId: BigNumberish, beneficiary: AddressLike],
    [IInheritanceCore.BeneficiaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimableETH"
  ): TypedContractMethod<
    [inheritanceId: BigNumberish, beneficiary: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInheritanceData"
  ): TypedContractMethod<
    [inheritanceId: BigNumberish],
    [IInheritanceCore.InheritanceDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInheritanceTiming"
  ): TypedContractMethod<
    [inheritanceId: BigNumberish],
    [ITimingManager.TimingConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalAssets"
  ): TypedContractMethod<
    [inheritanceId: BigNumberish],
    [IInheritanceCore.AssetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCustomTiming"
  ): TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      vestingSeconds: BigNumberish,
      delaySeconds: BigNumberish,
      cliffSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProductionMode"
  ): TypedContractMethod<[inheritanceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTestingMode"
  ): TypedContractMethod<[inheritanceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimingManager"
  ): TypedContractMethod<[_timingManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "timingManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "triggerInheritance"
  ): TypedContractMethod<[inheritanceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateInheritanceTiming"
  ): TypedContractMethod<
    [
      inheritanceId: BigNumberish,
      minVestingDuration: BigNumberish,
      executionDelay: BigNumberish,
      cliffDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AssetClaimed"
  ): TypedContractEvent<
    AssetClaimedEvent.InputTuple,
    AssetClaimedEvent.OutputTuple,
    AssetClaimedEvent.OutputObject
  >;
  getEvent(
    key: "AssetDeposited"
  ): TypedContractEvent<
    AssetDepositedEvent.InputTuple,
    AssetDepositedEvent.OutputTuple,
    AssetDepositedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryAdded"
  ): TypedContractEvent<
    BeneficiaryAddedEvent.InputTuple,
    BeneficiaryAddedEvent.OutputTuple,
    BeneficiaryAddedEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceCompleted"
  ): TypedContractEvent<
    InheritanceCompletedEvent.InputTuple,
    InheritanceCompletedEvent.OutputTuple,
    InheritanceCompletedEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceCreated"
  ): TypedContractEvent<
    InheritanceCreatedEvent.InputTuple,
    InheritanceCreatedEvent.OutputTuple,
    InheritanceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceTriggered"
  ): TypedContractEvent<
    InheritanceTriggeredEvent.InputTuple,
    InheritanceTriggeredEvent.OutputTuple,
    InheritanceTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AssetClaimed(uint256,address,uint8,address,uint256,uint256[],uint256)": TypedContractEvent<
      AssetClaimedEvent.InputTuple,
      AssetClaimedEvent.OutputTuple,
      AssetClaimedEvent.OutputObject
    >;
    AssetClaimed: TypedContractEvent<
      AssetClaimedEvent.InputTuple,
      AssetClaimedEvent.OutputTuple,
      AssetClaimedEvent.OutputObject
    >;

    "AssetDeposited(uint256,uint8,address,uint256,uint256[],uint256)": TypedContractEvent<
      AssetDepositedEvent.InputTuple,
      AssetDepositedEvent.OutputTuple,
      AssetDepositedEvent.OutputObject
    >;
    AssetDeposited: TypedContractEvent<
      AssetDepositedEvent.InputTuple,
      AssetDepositedEvent.OutputTuple,
      AssetDepositedEvent.OutputObject
    >;

    "BeneficiaryAdded(uint256,address,uint256,uint256)": TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;
    BeneficiaryAdded: TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;

    "InheritanceCompleted(uint256,uint256)": TypedContractEvent<
      InheritanceCompletedEvent.InputTuple,
      InheritanceCompletedEvent.OutputTuple,
      InheritanceCompletedEvent.OutputObject
    >;
    InheritanceCompleted: TypedContractEvent<
      InheritanceCompletedEvent.InputTuple,
      InheritanceCompletedEvent.OutputTuple,
      InheritanceCompletedEvent.OutputObject
    >;

    "InheritanceCreated(uint256,address,string,uint256)": TypedContractEvent<
      InheritanceCreatedEvent.InputTuple,
      InheritanceCreatedEvent.OutputTuple,
      InheritanceCreatedEvent.OutputObject
    >;
    InheritanceCreated: TypedContractEvent<
      InheritanceCreatedEvent.InputTuple,
      InheritanceCreatedEvent.OutputTuple,
      InheritanceCreatedEvent.OutputObject
    >;

    "InheritanceTriggered(uint256,address,uint256)": TypedContractEvent<
      InheritanceTriggeredEvent.InputTuple,
      InheritanceTriggeredEvent.OutputTuple,
      InheritanceTriggeredEvent.OutputObject
    >;
    InheritanceTriggered: TypedContractEvent<
      InheritanceTriggeredEvent.InputTuple,
      InheritanceTriggeredEvent.OutputTuple,
      InheritanceTriggeredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
