/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InheritanceLibInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_DEADLINE_EXTENSION"
      | "MAX_DEADLINE_EXTENSION"
      | "MIN_DEADLINE_EXTENSION"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_DEADLINE_EXTENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DEADLINE_EXTENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DEADLINE_EXTENSION",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_DEADLINE_EXTENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEADLINE_EXTENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DEADLINE_EXTENSION",
    data: BytesLike
  ): Result;
}

export interface InheritanceLib extends BaseContract {
  connect(runner?: ContractRunner | null): InheritanceLib;
  waitForDeployment(): Promise<this>;

  interface: InheritanceLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_DEADLINE_EXTENSION: TypedContractMethod<[], [bigint], "view">;

  MAX_DEADLINE_EXTENSION: TypedContractMethod<[], [bigint], "view">;

  MIN_DEADLINE_EXTENSION: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_DEADLINE_EXTENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DEADLINE_EXTENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DEADLINE_EXTENSION"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
