/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEmergencyManager } from "./IEmergencyManager";
export type { IInheritanceCore } from "./IInheritanceCore";
export type { ITimingManager } from "./ITimingManager";
